// Question Types
// 1. MCQs | Multiple Choice | single

export const python = {
    topic: 'Python',
    level: 'Beginner',
    totalQuestions: 21,
    perQuestionScore: 2,
    questions: [
        {
          question: 'What is the correct way to create a variable in Python?',
          choices: ['var x = 10', 'let x = 10', 'x = 10', 'int x = 10'],
          type: 'MCQs',
          correctAnswer: 'x = 10',
        },
        {
          question: 'Which of the following is used to define a function in Python?',
          choices: ['function', 'def', 'func', 'define'],
          type: 'MCQs',
          correctAnswer: 'def',
        },
        {
          question: 'How do you write a single-line comment in Python?',
          choices: ['// This is a comment', '# This is a comment', '/* This is a comment */', '-- This is a comment'],
          type: 'MCQs',
          correctAnswer: '# This is a comment',
        },
        {
          question: 'Which of the following data types is mutable in Python?',
          choices: ['int', 'tuple', 'list', 'string'],
          type: 'MCQs',
          correctAnswer: 'list',
        },
        {
          question: 'What will be the output of `print(2 ** 3)` in Python?',
          choices: ['5', '6', '8', '9'],
          type: 'MCQs',
          correctAnswer: '8',
        },
        {
          question: 'How can you read input from the user in Python?',
          choices: ['input()', 'read()', 'scan()', 'get()'],
          type: 'MCQs',
          correctAnswer: 'input()',
        },
        {
          question: 'Which of the following is used to handle exceptions in Python?',
          choices: ['try-except', 'catch-finally', 'handle-exception', 'error-try'],
          type: 'MCQs',
          correctAnswer: 'try-except',
        },
        {
          question: 'What keyword is used to exit a loop in Python?',
          choices: ['stop', 'break', 'exit', 'return'],
          type: 'MCQs',
          correctAnswer: 'break',
        },
        {
          question: 'How do you concatenate two strings in Python?',
          choices: ['str1 + str2', 'str1.concat(str2)', 'str1.append(str2)', 'str1 & str2'],
          type: 'MCQs',
          correctAnswer: 'str1 + str2',
        },
        {
          question: 'Which method is used to convert a string to an integer in Python?',
          choices: ['int()', 'str()', 'float()', 'convert()'],
          type: 'MCQs',
          correctAnswer: 'int()',
        },
        {
          question: 'What is the output of `len([1, 2, 3])` in Python?',
          choices: ['2', '3', '4', 'Error'],
          type: 'MCQs',
          correctAnswer: '3',
        },
        {
          question: 'How do you access the first element of a list named `my_list` in Python?',
          choices: ['my_list[0]', 'my_list(0)', 'my_list.first()', 'my_list.get(0)'],
          type: 'MCQs',
          correctAnswer: 'my_list[0]',
        },
        {
          question: 'Which of the following is a Python built-in data type?',
          choices: ['Array', 'List', 'Set', 'Queue'],
          type: 'MCQs',
          correctAnswer: 'List',
        },
        {
          question: 'What will be the result of `3 // 2` in Python?',
          choices: ['1.5', '1', '2', '0'],
          type: 'MCQs',
          correctAnswer: '1',
        },
        {
          question: 'Which Python library is commonly used for data manipulation?',
          choices: ['numpy', 'pandas', 'matplotlib', 'scipy'],
          type: 'MCQs',
          correctAnswer: 'pandas',
        },
        {
          question: 'What does the `range()` function do in Python?',
          choices: ['Generates a list of numbers', 'Returns a number', 'Creates a string', 'Generates a sequence of numbers'],
          type: 'MCQs',
          correctAnswer: 'Generates a sequence of numbers',
        },
        {
          question: 'How do you check the type of a variable in Python?',
          choices: ['type(variable)', 'check(variable)', 'typeof(variable)', 'variable.type()'],
          type: 'MCQs',
          correctAnswer: 'type(variable)',
        },
        {
          question: 'Which operator is used for exponentiation in Python?',
          choices: ['^', '**', 'exp', 'pow'],
          type: 'MCQs',
          correctAnswer: '**',
        },
        {
          question: 'How do you open a file in Python for writing?',
          choices: ['open("file.txt", "w")', 'open("file.txt", "r")', 'open("file.txt", "a")', 'open("file.txt", "rw")'],
          type: 'MCQs',
          correctAnswer: 'open("file.txt", "w")',
        },
        {
          question: 'Which of the following is the correct way to define a class in Python?',
          choices: ['class MyClass():', 'class MyClass:', 'define class MyClass:', 'MyClass class:'],
          type: 'MCQs',
          correctAnswer: 'class MyClass():',
        },
        {
          question: 'What is the correct syntax for an if statement in Python?',
          choices: ['if condition:', 'if condition then:', 'if (condition):', 'if condition then'],
          type: 'MCQs',
          correctAnswer: 'if condition:',
        }
      
    ],
  }

  export const linux = {
    topic: 'linux',
    level: 'Beginner',
    totalQuestions: 20,
    perQuestionScore: 5,
    questions: [
    {
      question: 'Which command is used to list files and directories in Linux?',
      choices: ['ls', 'list', 'dir', 'show'],
      type: 'MCQs',
      correctAnswer: 'ls',
    },
    {
      question: 'What does the `pwd` command do?',
      choices: ['Print working directory', 'Print working document', 'Print with date', 'Print workspace directory'],
      type: 'MCQs',
      correctAnswer: 'Print working directory',
    },
    {
      question: 'Which command is used to change the directory in Linux?',
      choices: ['cd', 'change', 'dir', 'move'],
      type: 'MCQs',
      correctAnswer: 'cd',
    },
    {
      question: 'How do you create a new directory in Linux?',
      choices: ['mkdir', 'mkdir', 'newdir', 'createdir'],
      type: 'MCQs',
      correctAnswer: 'mkdir',
    },
    {
      question: 'What command is used to display the contents of a file in Linux?',
      choices: ['cat', 'show', 'display', 'print'],
      type: 'MCQs',
      correctAnswer: 'cat',
    },
    {
      question: 'Which command is used to copy files in Linux?',
      choices: ['cp', 'copy', 'clone', 'duplicate'],
      type: 'MCQs',
      correctAnswer: 'cp',
    },
    {
      question: 'What does the `rm` command do?',
      choices: ['Remove files', 'Rename files', 'Move files', 'Read files'],
      type: 'MCQs',
      correctAnswer: 'Remove files',
    },
    {
      question: 'How can you view the current running processes in Linux?',
      choices: ['ps', 'top', 'list', 'process'],
      type: 'MCQs',
      correctAnswer: 'ps',
    },
    {
      question: 'Which command is used to display disk usage in Linux?',
      choices: ['df', 'du', 'disk', 'usage'],
      type: 'MCQs',
      correctAnswer: 'df',
    },
    {
      question: 'What does the `chmod` command do?',
      choices: ['Change file permissions', 'Change file owner', 'Change file name', 'Change file location'],
      type: 'MCQs',
      correctAnswer: 'Change file permissions',
    },
    {
      question: 'How do you search for a specific text in a file?',
      choices: ['grep', 'find', 'search', 'locate'],
      type: 'MCQs',
      correctAnswer: 'grep',
    },
    {
      question: 'Which command is used to move or rename files in Linux?',
      choices: ['mv', 'move', 'rename', 'change'],
      type: 'MCQs',
      correctAnswer: 'mv',
    },
    {
      question: 'What does the `echo` command do?',
      choices: ['Display text', 'Create files', 'Edit files', 'Delete files'],
      type: 'MCQs',
      correctAnswer: 'Display text',
    },
    {
      question: 'Which command displays the manual for a command in Linux?',
      choices: ['man', 'help', 'guide', 'info'],
      type: 'MCQs',
      correctAnswer: 'man',
    },
    {
      question: 'How do you display the last few lines of a file?',
      choices: ['tail', 'head', 'last', 'end'],
      type: 'MCQs',
      correctAnswer: 'tail',
    },
    {
      question: 'What does the `sudo` command do?',
      choices: ['Execute a command with superuser privileges', 'Show user details', 'Change user', 'Update system'],
      type: 'MCQs',
      correctAnswer: 'Execute a command with superuser privileges',
    },
    {
      question: 'Which file contains user account information in Linux?',
      choices: ['/etc/passwd', '/etc/group', '/etc/shadow', '/etc/users'],
      type: 'MCQs',
      correctAnswer: '/etc/passwd',
    },
    {
      question: 'What command is used to display the system’s current date and time?',
      choices: ['date', 'time', 'clock', 'now'],
      type: 'MCQs',
      correctAnswer: 'date',
    },
    {
      question: 'How do you find out the current user in Linux?',
      choices: ['whoami', 'current', 'user', 'who'],
      type: 'MCQs',
      correctAnswer: 'whoami',
    },
    {
      question: 'Which command is used to display a list of all the users currently logged in?',
      choices: ['who', 'users', 'login', 'active'],
      type: 'MCQs',
      correctAnswer: 'who',
    },
    {
      question: 'How do you view hidden files in a directory?',
      choices: ['ls -a', 'ls -l', 'list -hidden', 'view -all'],
      type: 'MCQs',
      correctAnswer: 'ls -a',
    }
  ]
}

export const os = {
    topic: 'Operating Systems',
    level: 'Advanced',
    totalQuestions: 15,
    perQuestionScore: 10,
    questions: [
        {
            question: 'Which scheduling algorithm prioritizes processes based on their expected CPU burst time?',
            choices: ['Round Robin', 'Shortest Job First', 'Priority Scheduling', 'Multilevel Queue'],
            type: 'MCQs',
            correctAnswer: 'Shortest Job First',
        },
        {
            question: 'In a deadlock situation, which of the following conditions is NOT required?',
            choices: ['Mutual Exclusion', 'Hold and Wait', 'No Preemption', 'Circular Wait'],
            type: 'MCQs',
            correctAnswer: 'No Preemption',
        },
        {
            question: 'What is the main purpose of virtual memory?',
            choices: ['Increase physical memory size', 'Allow processes to use more memory than physically available', 'Speed up memory access', 'Allocate CPU time efficiently'],
            type: 'MCQs',
            correctAnswer: 'Allow processes to use more memory than physically available',
        },
        {
            question: 'Which page replacement algorithm replaces the page that has been in memory the longest?',
            choices: ['Least Recently Used', 'First-In-First-Out', 'Optimal Page Replacement', 'Random Replacement'],
            type: 'MCQs',
            correctAnswer: 'First-In-First-Out',
        },
        {
            question: 'What does the `exec` system call do in Unix-like operating systems?',
            choices: ['Creates a new process', 'Replaces the current process image with a new process image', 'Terminates a process', 'Suspends a process'],
            type: 'MCQs',
            correctAnswer: 'Replaces the current process image with a new process image',
        },
        {
            question: 'In which scheduling algorithm do processes share CPU time in equal time slices?',
            choices: ['Round Robin', 'Shortest Job First', 'Priority Scheduling', 'Multilevel Feedback Queue'],
            type: 'MCQs',
            correctAnswer: 'Round Robin',
        },
        {
            question: 'What is thrashing in the context of virtual memory management?',
            choices: ['Excessive page faults leading to high paging activity', 'A process waiting indefinitely for a resource', 'An algorithm for page replacement', 'A state where CPU utilization is maximized'],
            type: 'MCQs',
            correctAnswer: 'Excessive page faults leading to high paging activity',
        },
        {
            question: 'Which of the following is NOT a characteristic of a semaphore?',
            choices: ['It can be used for mutual exclusion', 'It can be used for process synchronization', 'It is implemented using hardware support', 'It can be used to signal between processes'],
            type: 'MCQs',
            correctAnswer: 'It is implemented using hardware support',
        },
        {
            question: 'What is the difference between a hard page fault and a soft page fault?',
            choices: ['A hard page fault involves disk access, while a soft page fault does not', 'A hard page fault is a result of a process termination, while a soft page fault is due to memory allocation', 'A hard page fault occurs when a page is found in memory, while a soft page fault requires additional processing', 'A hard page fault is resolved by the operating system, while a soft page fault is handled by the hardware'],
            type: 'MCQs',
            correctAnswer: 'A hard page fault involves disk access, while a soft page fault does not',
        },
        {
            question: 'What is the primary purpose of a context switch in an operating system?',
            choices: ['To switch between user and kernel modes', 'To save and restore the state of a process', 'To handle page faults', 'To manage file system operations'],
            type: 'MCQs',
            correctAnswer: 'To save and restore the state of a process',
        },
        {
            question: 'Which of the following is a key feature of the Least Recently Used (LRU) page replacement algorithm?',
            choices: ['It replaces the page that has not been used for the longest time', 'It replaces the page that was most recently used', 'It replaces the page that is closest to being used', 'It randomly replaces pages in memory'],
            type: 'MCQs',
            correctAnswer: 'It replaces the page that has not been used for the longest time',
        },
        {
            question: 'Which of the following conditions is not a requirement for deadlock to occur?',
            choices: ['Mutual Exclusion', 'Hold and Wait', 'No Preemption', 'Circular Wait'],
            type: 'MCQs',
            correctAnswer: 'No Preemption',
        },
        {
            question: 'In a multi-level feedback queue scheduling algorithm, what is the primary objective?',
            choices: ['Minimizing turnaround time', 'Ensuring equal CPU time for all processes', 'Adjusting process priority dynamically based on behavior', 'Maximizing throughput'],
            type: 'MCQs',
            correctAnswer: 'Adjusting process priority dynamically based on behavior',
        },
        {
            question: 'What is the purpose of the `wait()` and `signal()` operations in synchronization?',
            choices: ['To control access to shared resources', 'To create new processes', 'To handle memory allocation', 'To manage file system operations'],
            type: 'MCQs',
            correctAnswer: 'To control access to shared resources',
        },
        {
            question: 'Which of the following file systems is primarily used in Unix-like operating systems?',
            choices: ['NTFS', 'FAT32', 'ext4', 'HFS+'],
            type: 'MCQs',
            correctAnswer: 'ext4',
        },
        {
            question: 'What is the main advantage of using a multi-level page table in memory management?',
            choices: ['Reduced memory consumption for page tables', 'Increased page fault rate', 'Simplified page replacement algorithms', 'Faster context switching'],
            type: 'MCQs',
            correctAnswer: 'Reduced memory consumption for page tables',
        }
    ]
};
  
export const c = {
    topic: 'C Programming',
    level: 'Beginner',
    totalQuestions: 30,
    perQuestionScore: 5,
    questions: [
        {
            question: 'Which of the following is the correct syntax for a `for` loop in C?',
            choices: ['for (i = 0; i < 10; i++)', 'for i = 0; i < 10; i++', 'for (i < 10; i++)', 'for (i = 0; i < 10)'],
            type: 'MCQs',
            correctAnswer: 'for (i = 0; i < 10; i++)',
        },
        {
            question: 'What is the default return type of a function in C if no return type is specified?',
            choices: ['int', 'void', 'char', 'float'],
            type: 'MCQs',
            correctAnswer: 'int',
        },
        {
            question: 'How do you declare a variable in C?',
            choices: ['int variable_name;', 'variable_name int;', 'declare int variable_name;', 'variable_name : int;'],
            type: 'MCQs',
            correctAnswer: 'int variable_name;',
        },
        {
            question: 'What is the purpose of the `#include` directive in C?',
            choices: ['To include standard or user-defined libraries', 'To declare variables', 'To define functions', 'To create a new header file'],
            type: 'MCQs',
            correctAnswer: 'To include standard or user-defined libraries',
        },
        {
            question: 'Which function is used to print text to the console in C?',
            choices: ['printf()', 'print()', 'write()', 'echo()'],
            type: 'MCQs',
            correctAnswer: 'printf()',
        },
        {
            question: 'What is the correct way to comment a single line in C?',
            choices: ['// This is a comment', '# This is a comment', '/* This is a comment */', '-- This is a comment'],
            type: 'MCQs',
            correctAnswer: '// This is a comment',
        },
        {
            question: 'How do you declare an integer array of size 10 in C?',
            choices: ['int arr[10];', 'int arr = 10;', 'int arr();', 'int arr[10]();'],
            type: 'MCQs',
            correctAnswer: 'int arr[10];',
        },
        {
            question: 'Which of the following is used to define a constant value in C?',
            choices: ['const', '#define', 'constant', 'static'],
            type: 'MCQs',
            correctAnswer: '#define',
        },
        {
            question: 'What will be the output of `printf("%d", 10 / 3);` in C?',
            choices: ['3.33', '3', '3.0', '0'],
            type: 'MCQs',
            correctAnswer: '3',
        },
        {
            question: 'How do you include a user-defined header file in C?',
            choices: ['#include "filename.h"', '#include <filename.h>', '#include filename.h', '#import "filename.h"'],
            type: 'MCQs',
            correctAnswer: '#include "filename.h"',
        },
        {
            question: 'Which operator is used to find the remainder of a division in C?',
            choices: ['/', '%', '*', '+'],
            type: 'MCQs',
            correctAnswer: '%',
        },
        {
            question: 'How do you declare a function that returns an integer and takes no arguments in C?',
            choices: ['int function_name();', 'void function_name();', 'int function_name(void);', 'int function_name(){}'],
            type: 'MCQs',
            correctAnswer: 'int function_name(void);',
        },
        {
            question: 'What is the size of an `int` in C on a 32-bit system?',
            choices: ['2 bytes', '4 bytes', '8 bytes', '1 byte'],
            type: 'MCQs',
            correctAnswer: '4 bytes',
        },
        {
            question: 'What does the `return` statement do in a function?',
            choices: ['Exits the function and optionally returns a value', 'Continues execution of the next statement', 'Defines a new function', 'Declares a variable'],
            type: 'MCQs',
            correctAnswer: 'Exits the function and optionally returns a value',
        },
        {
            question: 'Which of the following is the correct syntax to declare a pointer in C?',
            choices: ['int *ptr;', 'int ptr*;', 'ptr int;', '*int ptr;'],
            type: 'MCQs',
            correctAnswer: 'int *ptr;',
        },
        {
            question: 'What does the `sizeof()` operator do in C?',
            choices: ['Returns the size of a data type or variable in bytes', 'Returns the value of a variable', 'Returns the length of a string', 'Returns the address of a variable'],
            type: 'MCQs',
            correctAnswer: 'Returns the size of a data type or variable in bytes',
        },
        {
            question: 'How do you access the value of a pointer in C?',
            choices: ['Using the * operator', 'Using the & operator', 'Using the -> operator', 'Using the . operator'],
            type: 'MCQs',
            correctAnswer: 'Using the * operator',
        },
        {
            question: 'What is the purpose of the `break` statement in a loop?',
            choices: ['To exit the loop immediately', 'To skip the current iteration and continue with the next', 'To pause the loop temporarily', 'To terminate the program'],
            type: 'MCQs',
            correctAnswer: 'To exit the loop immediately',
        },
        {
            question: 'Which loop will execute at least once regardless of the condition?',
            choices: ['for', 'while', 'do-while', 'foreach'],
            type: 'MCQs',
            correctAnswer: 'do-while',
        },
        {
            question: 'What is the use of the `switch` statement in C?',
            choices: ['To execute one block of code among many choices based on a value', 'To loop through a block of code', 'To handle file operations', 'To perform arithmetic operations'],
            type: 'MCQs',
            correctAnswer: 'To execute one block of code among many choices based on a value',
        },
        {
            question: 'How do you concatenate two strings in C?',
            choices: ['Using strcat()', 'Using concat()', 'Using append()', 'Using merge()'],
            type: 'MCQs',
            correctAnswer: 'Using strcat()',
        },
        {
            question: 'Which of the following is the correct way to initialize an array of 5 integers in C?',
            choices: ['int arr[] = {1, 2, 3, 4, 5};', 'int arr = {1, 2, 3, 4, 5};', 'int arr[5] = {1, 2, 3, 4, 5};', 'int arr(5) = {1, 2, 3, 4, 5};'],
            type: 'MCQs',
            correctAnswer: 'int arr[] = {1, 2, 3, 4, 5};',
        },
        {
            question: 'What is the correct syntax for a comment block in C?',
            choices: ['/* This is a comment */', '// This is a comment', '/* This is a comment', '// This is a comment */'],
            type: 'MCQs',
            correctAnswer: '/* This is a comment */',
        },
        {
            question: 'How do you read a single character from the user in C?',
            choices: ['scanf("%c", &char_variable);', 'read("%c", char_variable);', 'input("%c", &char_variable);', 'char_variable = read();'],
            type: 'MCQs',
            correctAnswer: 'scanf("%c", &char_variable);',
        },
        {
            question: 'Which function is used to allocate dynamic memory in C?',
            choices: ['malloc()', 'alloc()', 'new()', 'get()'],
            type: 'MCQs',
            correctAnswer: 'malloc()',
        },
        {
            question: 'What is the purpose of the `continue` statement in a loop?',
            choices: ['To skip the current iteration and continue with the next iteration', 'To exit the loop', 'To terminate the program', 'To pause the loop'],
            type: 'MCQs',
            correctAnswer: 'To skip the current iteration and continue with the next iteration',
        },
        {
            question: 'How do you declare a structure in C?',
            choices: ['struct structure_name { data_type member1; data_type member2; };', 'struct { data_type member1; data_type member2; } structure_name;', 'structure structure_name { data_type member1; data_type member2; };', 'struct structure_name { member1 data_type; member2 data_type; };'],
            type: 'MCQs',
            correctAnswer: 'struct structure_name { data_type member1; data_type member2; };',
        },
        {
            question: 'What is the correct way to declare a constant variable in C?',
            choices: ['const int x = 10;', '#define x 10;', 'int const x = 10;', 'constant int x = 10;'],
            type: 'MCQs',
            correctAnswer: 'const int x = 10;',
        },
        {
            question: 'Which of the following is the correct syntax to include a library in C?',
            choices: ['#include <library.h>', '#include "library.h"', '#include library.h', '#include (library.h)'],
            type: 'MCQs',
            correctAnswer: '#include <library.h>',
        },
        {
            question: 'What is the purpose of the `sizeof` operator in C?',
            choices: ['To determine the size of a data type or variable in bytes', 'To find the length of a string', 'To get the value of a variable', 'To allocate memory dynamically'],
            type: 'MCQs',
            correctAnswer: 'To determine the size of a data type or variable in bytes',
        },
        {
            question: 'How do you declare a function prototype in C?',
            choices: ['return_type function_name(parameters);', 'function_name(parameters);', 'return_type function_name();', 'function_name(parameters) {}'],
            type: 'MCQs',
            correctAnswer: 'return_type function_name(parameters);',
        },
        {
            question: 'What is the output of `printf("%d", 3 + 4 * 2);` in C?',
            choices: ['11', '14', '10', '8'],
            type: 'MCQs',
            correctAnswer: '11',
        },
        {
            question: 'What is the function of the `free()` function in C?',
            choices: ['To deallocate previously allocated memory', 'To allocate new memory', 'To initialize a variable', 'To read input from the user'],
            type: 'MCQs',
            correctAnswer: 'To deallocate previously allocated memory',
        },
        {
            question: 'How do you access the members of a structure in C?',
            choices: ['Using the . operator', 'Using the -> operator', 'Using the * operator', 'Using the & operator'],
            type: 'MCQs',
            correctAnswer: 'Using the . operator',
        },
        {
            question: 'Which keyword is used to create a new data type in C?',
            choices: ['typedef', 'new', 'struct', 'enum'],
            type: 'MCQs',
            correctAnswer: 'typedef',
        },
        {
            question: 'What is the purpose of the `#include <stdio.h>` directive?',
            choices: ['To include the standard input/output library', 'To define constants', 'To include user-defined functions', 'To manage memory allocation'],
            type: 'MCQs',
            correctAnswer: 'To include the standard input/output library',
        },
        {
            question: 'What does the `&` operator do in C?',
            choices: ['It returns the address of a variable', 'It performs a bitwise AND operation', 'It concatenates two strings', 'It dereferences a pointer'],
            type: 'MCQs',
            correctAnswer: 'It returns the address of a variable',
        },
        {
            question: 'How do you write an infinite loop in C?',
            choices: ['while(1)', 'for(;;)', 'for(1;1;1)', 'while(0)'],
            type: 'MCQs',
            correctAnswer: 'while(1)',
        },
        {
            question: 'What will be the output of `printf("%f", 5/2);` in C?',
            choices: ['2.5', '2.0', '2.50', '3'],
            type: 'MCQs',
            correctAnswer: '2.0',
        },
        {
            question: 'Which of the following is a valid way to declare a constant pointer to an integer?',
            choices: ['const int *ptr;', 'int *const ptr;', 'const int ptr*;', 'int const *ptr;'],
            type: 'MCQs',
            correctAnswer: 'int *const ptr;',
        },
        {
            question: 'Which function is used to terminate a C program?',
            choices: ['exit()', 'return()', 'end()', 'terminate()'],
            type: 'MCQs',
            correctAnswer: 'exit()',
        },
        {
            question: 'How do you declare a 2D array in C?',
            choices: ['int arr[3][4];', 'int arr[4,3];', 'int arr(3,4);', 'int arr[] = {3,4};'],
            type: 'MCQs',
            correctAnswer: 'int arr[3][4];',
        },
        {
            question: 'What will be the result of the expression `5 == 5` in C?',
            choices: ['1', '0', 'True', 'False'],
            type: 'MCQs',
            correctAnswer: '1',
        },
        {
            question: 'Which of the following operators has the highest precedence in C?',
            choices: ['*', '+', '-', '/', '=='],
            type: 'MCQs',
            correctAnswer: '*',
        },
        {
            question: 'What is the purpose of the `scanf()` function in C?',
            choices: ['To read input from the user', 'To print output to the console', 'To allocate memory dynamically', 'To initialize variables'],
            type: 'MCQs',
            correctAnswer: 'To read input from the user',
        },
        {
            question: 'Which header file is required to use the `printf()` and `scanf()` functions in C?',
            choices: ['<stdio.h>', '<stdlib.h>', '<conio.h>', '<math.h>'],
            type: 'MCQs',
            correctAnswer: '<stdio.h>',
        },
        {
            question: 'What is the result of the expression `10 % 3` in C?',
            choices: ['3', '1', '10', '0'],
            type: 'MCQs',
            correctAnswer: '1',
        },
        {
            question: 'How do you declare a floating-point variable in C?',
            choices: ['float variable_name;', 'int variable_name;', 'double variable_name;', 'char variable_name;'],
            type: 'MCQs',
            correctAnswer: 'float variable_name;',
        },
        {
            question: 'What does the `return 0;` statement signify in the `main()` function?',
            choices: ['Successful completion of the program', 'Failure of the program', 'End of file reached', 'Termination of a loop'],
            type: 'MCQs',
            correctAnswer: 'Successful completion of the program',
        }
    ]
};
